### ISSUE TITLE
mismatch function names

### ISSUE THREAD

**Issue by JoshLitt** [realgud/realgud-jdb#1]
I'm unable to run this version (realgud-jdb-20190525.357) from elpa. Commit 14918c8, changed references from `realgud--jdb-query-cmdline` and `realgud--jdb-parse-cmd-args` to `realgud:jdb-query-cmdline` and `realgud:jdb-parse-cmd-args`, but did not change the `defun`s in `core.el` to match. At least in Emacs 25.3, this causes the library to not run.

https://github.com/realgud/realgud-jdb/blob/5e3211a17a8282d2d0027e73149e01034082bc41/realgud-jdb/jdb.el#L87-L89

**Comment by JoshLitt** [comment]
Actually, looks like this versoin 20190525.357 is just not ready for prime-time. I have `caddr undefined` (simple enough to work around), `realgud--track-set-debugger undefined` (should be realgud:track-set-debugger).

**Comment by rocky** [comment]
> Actually, looks like this versoin 20190525.357 is just not ready for prime-time.

Yeah, but I'm not sure any version of this was ever ready for prime time. And have you used this in `gud`? If so, what was it like? 

I put it here in the hope others will take what's there run with it and improve it. 

I think I've gotten all of the issues out, but if not, feel free to reopen or better open another issue. 

And _contratulations_! You are the first person in the 4 years or so that this started who has shown any interest, enough to open a bug report.

**Comment by JoshLitt** [comment]
Ha hah. Well, maybe I incorrectly believed I was using this before and just updated. Who knows. I'll let you know if it works or not for me.

**Comment by rocky** [comment]
Ok. Well, I might have used this once or twice too. It had been in realgud, but in order to better decentralize things, I've split it out into a separate package.
