### ISSUE TITLE
Trying to understand the relationship between realgud-jdb and realgud:jdb

### ISSUE THREAD

**Issue by johnutz-PNSR** [realgud/realgud-jdb#2]
Hi Rocky, et all;

I am trying to use realgud's jdb support. However, it's not clear how to go about this. I suspect realgud-jdb is the correct way to go because it's newer than the wiki entry from 2015 that indicates that i should be invoking realgud:jdb *and* the invocation of realgud:jdb is commented out in the realgud tree.

going down the realgud-jdb path, i get stuck pretty quickly:

Do i do a load lib of realgud before invoking realgud-jdb? Or does realgud-jdb pull in the things it needs from realgud when i invoke it? (M-x realgud-jdb is what i mean by invoke).
But i also notice that realgud--jdb is a function that shows up sometimes when i am trying to invoke realgud-jdb.

So, if i have a java class impl called SortXY.java and i compile it with javac -g SortXY.java and that results in SortXY.class, what arguments do i pass to jdb to successfully load SortXY.class?
Thankyou for any help yuu can provide.

Also, should the wiki page from 2015 that discusses how to use realgud:jdb be changed to correctly reflect the current state of affairs?

tnx!

johnu

**Comment by rocky** [comment]
> I am trying to use realgud's jdb support. 

The wiki entry from 2005 you cite starts off: 

> realgud--jdb support is experimental. That means it is flaky and largely untested.

I have corrected the name `realgud:jdb` to be `realgud--jdb` but otherwise things stay the same as they were in 2005.

A good part of the reason this is so primitive is that no one has shown interest. Look at the star rating and compare that with my other projects https://github.com/rocky and you'll se this is pretty much at the bottom of the heap. (I've just upvoted this project today myself, to show some interest, however small) 

> Do i do a load lib of realgud before invoking realgud-jdb? Or does realgud-jdb pull in the things it needs from realgud when i invoke it? (M-x realgud-jdb is what i mean by invoke).
But i also notice that realgud--jdb is a function that shows up sometimes when i am trying to invoke realgud-jdb.

Some of this is jumbled and I am not sure I understand you. The way all emacs _packages_ work is that they load whatever dependent packages are needed. So, specifically, when you `load-library realgud-jdb` , `require` `realgud` is pulled in.  `realgud--jdb` (note two dashes) is a command. (All commands are also functions). So you run `realgud--jdb` (no colon, two dashes) as it should (now) say in the wiki entry. 

I just tried what I wrote back in 2005, and all of that more or less still works after modifying the name from `realgud:jdb` to `realgud--jdb`. (The Emacs Language standards facists insist on the the double dash instead of the colon. I just forgot to update the name in the wiki.)

Some small corrections to this repository were made to get this to work. Presumably Melpa unstable will pick that up soon. Or be sure to refresh this repository. 

> Also, should the wiki page from 2015 that discusses how to use realgud:jdb be changed to correctly reflect the current state of affairs?

Yes it should. I've just corrected mistakes I noticed. However I have no doubt things can be improved, so feel free to show support and fix things as you find them. That's one aspect about open source - it is only as good as those who are willing to work on it.  So if you find something is confusing or think you can improve or clarify the documents, please do. 

I suppose that jdb notes should be copied from that wiki to this one, now that the two repositories have been split out.  If that's done, it would be nice to add a link from that to here. I believe anyone can do this - it doesn't (and shouldn't have to be) me.

**Comment by johnutz-PNSR** [comment]
Hi Rocky!

Thankyou for the prompt and thoughtful response. It was all that i hoped for.

The jumbledness of the question wsa reflective of the state of my tiny and disordered mind. :-)

I will upvote this too and i'll try out what you have told me and happily update the wiki accordingly. Hopefully our new Redmond Overlord's infrastructure will note our combined activity and put it in front of a few more people.


John L. Utz III<mailto:john.utz@pensardevelopment.com>   |   Pensar Development<http://www.pensardevelopment.com/>   | 206.747.5497

This email message may contain confidential and proprietary information.  Any unauthorized use is prohibited.
EXPORT OR RE-EXPORT OF INFORMATION CONTAINED HEREIN MAY BE SUBJECT TO RESTRICTIONS AND REQUIREMENTS OF U.S. EXPORT LAWS AND REGULATIONS, AND MAY REQUIRE ADVANCE AUTHORIZATION FROM THE U.S. GOVERNMENT. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

________________________________

**Comment by johnutz-PNSR** [comment]
Oh afurther comments: i found out about realgud jdb from Matsubara Yutaka aka mopemope who has written a pretty useful java completion tool called meghanada (i have no idea why he picked that name). His answer to 'how do i debug with meghanada' is 'meghanada has no debugger, use realgud'


John L. Utz III<mailto:john.utz@pensardevelopment.com>   |   Pensar Development<http://www.pensardevelopment.com/>   | 206.747.5497

This email message may contain confidential and proprietary information.  Any unauthorized use is prohibited.
EXPORT OR RE-EXPORT OF INFORMATION CONTAINED HEREIN MAY BE SUBJECT TO RESTRICTIONS AND REQUIREMENTS OF U.S. EXPORT LAWS AND REGULATIONS, AND MAY REQUIRE ADVANCE AUTHORIZATION FROM THE U.S. GOVERNMENT. If you are not the intended recipient, please contact the sender by reply email and destroy all copies of the original message.

________________________________

**Comment by rocky** [comment]
Not sure there's anything actionable to do here, so closing. 

If I missed something either reopen or open a new issue with whatever remains.
